/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import Entidades.reserva;
import accesoadatos.huespeddata;
import accesoadatos.reservadata;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author bmt
 */
public class editarreserva extends javax.swing.JInternalFrame {

    /**
     * Creates new form editarreserva
     */
    private int dni;
    private DefaultTableModel modelotabla = new DefaultTableModel();
    reservadata res=new reservadata();
    
    public editarreserva(int dni) {
        initComponents();
        armarcabecera();
        this.dni=dni;
        llenarcampos(res.buscarreservadni(dni));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        jLabel1.setText("Seleccione una reserva:");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jButton1.setText("Salir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Abortar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 396, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
        if(jTable1.getSelectedRow()==-1){
            JOptionPane.showMessageDialog(null,"Debe seleccionar una fila de la tabla");
        }else{
            
            if(jTable1.getSelectedRowCount()>1){
                
                JOptionPane.showMessageDialog(null,"Seleccione sólo una fila de la columna");
                
            }else{
            
            if(jTable1.getComponentAt(jTable1.getSelectedRow(),3).toString().equals("En curso")){
                JOptionPane.showMessageDialog(null,"Dado que el estado de la reserva seleccionada es 'En curso', la misma será abortada parcialmente el día de hoy");
            }else{
                JOptionPane.showMessageDialog(null,"Dado que el estado de la reserva seleccionada es 'Futura', la misma será abortada totalmente");
            }
            
        
        int el=elementosselecionados(res.buscarreservadni(dni)).get(jTable1.getSelectedRow());
            
            
        res.abortarreserva(res.buscarreservadni(dni).get(el));
        
        
        
//        JOptionPane.showMessageDialog(null,);

        
        this.setVisible(false);
        
            }
        
        
        }
        
        
        
        
        
        
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables

    private void armarcabecera(){
            modelotabla.addColumn("ID habitación");
            modelotabla.addColumn("Fecha checkin");
            modelotabla.addColumn("Decha checkout");
            modelotabla.addColumn("Estado");
            
            jTable1.setModel(modelotabla);
        }

    public void llenarcampos(ArrayList<reserva> res){
        huespeddata hues =new huespeddata();
        Object[] vector = new Object[4];
        for(int i=0;i<=res.size()-1;i++){
            if(res.get(i).getEstadoreserva().equals("En curso") || res.get(i).getEstadoreserva().equals("Futura")){
                vector[0]=res.get(i).getHabitacion().getIdhabitacion();
                vector[1]=res.get(i).getCheckin();
                vector[2]=res.get(i).getCheckout();
                vector[3]=res.get(i).getEstadoreserva();
            }
            modelotabla.addRow(vector);
        }
//        modelotabla.addRow(vector);
    }
    
    
    public ArrayList<Integer> elementosselecionados(ArrayList<reserva> res){
        huespeddata hues =new huespeddata();
        ArrayList<Integer> elementos = new ArrayList();
        int elemento;
        Object[] vector = new Object[4];
        for(int i=0;i<=res.size()-1;i++){
            if(res.get(i).getEstadoreserva().equals("En curso") || res.get(i).getEstadoreserva().equals("Futura")){
                vector[0]=res.get(i).getHabitacion().getIdhabitacion();
                vector[1]=res.get(i).getCheckin();
                vector[2]=res.get(i).getCheckout();
                vector[3]=res.get(i).getEstadoreserva();
                elemento=i;
                elementos.add(elemento);
            }
        }
        return elementos;
        
        
        
    }
    
    
}
