/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import accesoadatos.habitaciondata;
import accesoadatos.huespeddata;
import accesoadatos.mantenimientodata;
import accesoadatos.reservadata;
import javax.swing.JMenuItem;
import javax.swing.JOptionPane;
import javax.swing.JPopupMenu;

/**
 *
 * @author bmt
 */
public class menuprincipal extends javax.swing.JFrame {

    /**
     * Creates new form menuprincipal
     */
    
    
//    JMenuItem jm1 = new JMenuItem("Abortar parcialmente");
//    JMenuItem jm2 = new JMenuItem("Abortar totalmente");

    
    
    
    
    public menuprincipal() {
        initComponents();

//
//        jMenuItem1.add(jm1);
//        jMenuItem1.add(jm2);
//        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        escritorio = new javax.swing.JDesktopPane();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        jMenuItem12 = new javax.swing.JMenuItem();
        jMenuItem11 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem7 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(700, 600));

        jButton1.setText("Actualizar datos");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Script MT Bold", 0, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("El Gran Hotel");

        escritorio.setLayer(jButton1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        escritorio.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout escritorioLayout = new javax.swing.GroupLayout(escritorio);
        escritorio.setLayout(escritorioLayout);
        escritorioLayout.setHorizontalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, escritorioLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
            .addGroup(escritorioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(119, Short.MAX_VALUE))
        );
        escritorioLayout.setVerticalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, escritorioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 161, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );

        jMenu1.setText("Reservas");
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });

        jMenuItem1.setText("Nueva reserva");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("Modificar reserva");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuItem3.setText("Setear precio");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenu6.setText("Buscar reserva");

        jMenuItem12.setText("Por huésped");
        jMenuItem12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem12ActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItem12);

        jMenuItem11.setText("Por fechas");
        jMenuItem11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem11ActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItem11);

        jMenu1.add(jMenu6);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Habitaciones");

        jMenu5.setText("Modificar precios");

        jMenuItem9.setText("Actualización por inflación");
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem9);

        jMenuItem10.setText("Cambio de precios relativos");
        jMenuItem10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem10ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem10);

        jMenu2.add(jMenu5);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Buscar clientes");

        jMenuItem7.setText("Buscar por DNI");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem7);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        
        escritorio.removeAll();
        escritorio.repaint();
        habitacionesdisp hd = new habitacionesdisp();
        hd.setVisible(true);
        escritorio.add(hd);
        escritorio.moveToFront(hd);
        
        
//        
//        JOptionPane.showInputDialog("hola");
//        
//        JOptionPane.
//        
//        int capacidad;
//        boolean error1;
//        boolean error2;
//        String capacidadtext;
//        
//        do{
//            
//            error1=false;
//            error2=false;
//            capacidadtext=JOptionPane.showInputDialog("Introduza la capacidad de la habitación:");
//            try{
//            capacidad = Integer.parseInt(capacidadtext);
//        } catch (NumberFormatException ex){
//            JOptionPane.showMessageDialog(null,"Debe ingresar un número entre 2 y 4");
//            error1=true;
//        }
//            if(error1=false){
//                if(capacidad<2 || capacidad>4){
//                   JOptionPane.showMessageDialog(null,"Debe ingresar un número entre 2 y 4"); 
//            }
//        }
//            
//            JOptionPane
//            
//        }while(error1==true || error2==true);
//       
//        
//        
//        
        
        
        
        
        
        
        
//        escritorio.removeAll();
//        escritorio.repaint();
//        habitacionesdisponibles hd = new habitacionesdisponibles();
//        hd.setVisible(true);
//        escritorio.add(hd);
//        escritorio.moveToFront(hd);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
//        JMenuItem pm= new JMenuItem("Abortar Reserva Totalmente");
//        pm.setVisible(true);}}

//                jp.setVisible(true);


//    String dnis;
//    int dni;
//    boolean exception=false;
//    boolean cancel=false;
//    
//    huespeddata hues = new huespeddata();
//    
//    do{
//        
//    
//    try{
//        dnis=JOptionPane.showInputDialog("Ingresar el DNI del cliente");
//        dni=Integer.parseInt(dnis);
//        if(hues.comprobarexistencia(dni)==true){
//            
//        }else{
//            JOptionPane.showMessageDialog(null,"No existen reservas registradas a nombre del huésped cuyo DNI ");
//        }
//    }catch(NumberFormatException nfe){
//        JOptionPane.showMessageDialog(null,"Debe ingresar un valor numérico");
//        exception=true;
//    }
//    
//    }while(exception==true);
//            
//            
        huespeddata hues=new huespeddata();
        boolean exception;
        String dni;
        dni=JOptionPane.showInputDialog("Ingresar el nro. de DNI del cliente a nombre de la reserva que desea modificar:");
        do{
            if(dni!=null){
                exception=false;
                try{
                    boolean existencia=hues.comprobarexistencia(Integer.parseInt(dni));
                    if(existencia==true){
                        escritorio.removeAll();
                        escritorio.repaint();
                        editarreserva er = new editarreserva(Integer.parseInt(dni));
                        er.setVisible(true);
                        escritorio.add(er);
                        escritorio.moveToFront(er);
                    }else{
                        JOptionPane.showMessageDialog(null,"No existe una reserva a nombre del cliente cuyo nro. de DNI es "+dni+" en la base de datos.");
                    }
                }catch(NumberFormatException ex){
                    JOptionPane.showMessageDialog(null,"Debe ingresar un valor numérico");
                    exception=true;
                    dni=JOptionPane.showInputDialog("Ingresar el nro. de DNI del cliente a nombre de la reserva que desea modificar:");
                }
            }else{
                exception=false;
            }
            
        }while(exception==true);
        
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem12ActionPerformed
        // TODO add your handling code here:
        
        huespeddata hues=new huespeddata();
        boolean exception;
        String dni;
        dni=JOptionPane.showInputDialog("Ingresar el nro. de DNI del cliente a nombre de la reserva que desea buscar:");
        do{
            if(dni!=null){
                exception=false;
                try{
                    boolean existencia=hues.comprobarexistencia(Integer.parseInt(dni));
                    if(existencia==true){
                        escritorio.removeAll();
                        escritorio.repaint();
                        buscarreserva br = new buscarreserva(Integer.parseInt(dni));
                        br.setVisible(true);
                        escritorio.add(br);
                        escritorio.moveToFront(br);
                    }else{
                        JOptionPane.showMessageDialog(null,"No existe una reserva a nombre del cliente cuyo nro. de DNI es "+dni+" en la base de datos.");
                    }
                }catch(NumberFormatException ex){
                    JOptionPane.showMessageDialog(null,"Debe ingresar un valor numérico");
                    exception=true;
                    dni=JOptionPane.showInputDialog("Ingresar el nro. de DNI del cliente a nombre de la reserva que desea modificar:");
                }
            }else{
                exception=false;
            }
            
        }while(exception==true);
        
        
        
    }//GEN-LAST:event_jMenuItem12ActionPerformed

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
        // TODO add your handling code here:
        habitaciondata hab = new habitaciondata();
        double indice;
        try{
        indice=Double.parseDouble(JOptionPane.showInputDialog("Ingrese el índice de inflación"));
        hab.actualizacionporinflacion(indice);
        }catch(NumberFormatException nfe){
            JOptionPane.showMessageDialog(null,"Debe ingresar un valor numérico. Utilice el punto ('.') para como separador decimal");
        }catch(NullPointerException npe){
            
        }
    }//GEN-LAST:event_jMenuItem9ActionPerformed

    private void jMenuItem10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem10ActionPerformed
        // TODO add your handling code here:
        escritorio.removeAll();
        escritorio.repaint();
        actualizacionpreciosrelativos apc = new actualizacionpreciosrelativos();
        apc.setVisible(true);
        escritorio.add(apc);
        escritorio.moveToFront(apc);
        
        
    }//GEN-LAST:event_jMenuItem10ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        habitaciondata hab=new habitaciondata();
        reservadata res=new reservadata();
        mantenimientodata mtto=new mantenimientodata();
        
        res.setearestadoreserva();
        mtto.setearestadomantenimiento();
        hab.setearestadohabitaciones();
        hab.setearlibrehasta();
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        // TODO add your handling code here:
        huespeddata hues=new huespeddata();
        boolean exception;
        String dni;
        dni=JOptionPane.showInputDialog("Ingresar el nro. de DNI del cliente que desea buscar:");
        do{
            if(dni!=null){
                exception=false;
                try{
                    boolean existencia=hues.comprobarexistencia(Integer.parseInt(dni));
                    if(existencia==true){
                       String mensaje1 = "Información del cliente con DNI " + dni + ":\n" +
                 "" + "\n" +             
                 "Nombre: " + hues.buscarhuespedpordni(Integer.parseInt(dni)).getNombre() + "\n" +
                 "Apellido: " + hues.buscarhuespedpordni(Integer.parseInt(dni)).getApellido() + "\n" +
                 "Pais: " + hues.buscarhuespedpordni(Integer.parseInt(dni)).getPais() + "\n" +
                 "Domicilio: " + hues.buscarhuespedpordni(Integer.parseInt(dni)).getDomicilio() + "\n" +
                 "Teléfono: " + hues.buscarhuespedpordni(Integer.parseInt(dni)).getTelefono() + "\n" +
                 "Email: " + hues.buscarhuespedpordni(Integer.parseInt(dni)).getEmail() + "\n";
                       JOptionPane.showMessageDialog(null,mensaje1);
                    }else{
                        JOptionPane.showMessageDialog(null,"No existe un cliente con DNI "+dni+" en la base de datos");
                    }
                }catch(NumberFormatException ex){
                    JOptionPane.showMessageDialog(null,"Debe ingresar un valor numérico");
                    exception=true;
                    dni=JOptionPane.showInputDialog("Ingresar el nro. de DNI del cliente a nombre de la reserva que desea modificar:");
                }
            }else{
                exception=false;
            }
            
        }while(exception==true);
        
        
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jMenuItem11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem11ActionPerformed
        // TODO add your handling code here:
        escritorio.removeAll();
        escritorio.repaint();
        buscarreservaporfecha brf = new buscarreservaporfecha();
        brf.setVisible(true);
        escritorio.add(brf);
        escritorio.moveToFront(brf);
    }//GEN-LAST:event_jMenuItem11ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menuprincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menuprincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menuprincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menuprincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menuprincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane escritorio;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem9;
    // End of variables declaration//GEN-END:variables



public void cerrarescritorio(){
    escritorio.removeAll();
    escritorio.repaint();
}

//    public void submenu(){
//        jMenuItem2.add(jp);
//    }


}
